version: "3.9"

services:
    database:
        image: postgres
        container_name: database_FinApi
        restart: always
        ports:
            - 5432:5432
            - 9229:9229
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=fin_api
        volumes:
            - pgdata:/data/postgres


    app:
        build: .
        container_name: fin_api
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database


volumes:
    pgdata:
        driver: local
